name: Build FFmpeg with dshow

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install MSYS2
      run: choco install -y msys2
      
    - name: Install dependencies
      shell: msys2 {0}
      run: |
        pacman -Sy --noconfirm --needed \
          mingw-w64-x86_64-toolchain \
          git \
          make \
          yasm \
          nasm
        
    - name: Configure FFmpeg
      shell: msys2 {0}
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git
        cd ffmpeg
        ./configure \
          --enable-dshow \
          --enable-gpl \
          --enable-version3 \
          --disable-w32threads \
          --enable-pthreads
        
    - name: Build FFmpeg
      shell: msys2 {0}
      run: |
        cd ffmpeg
        make -j$(nproc)
        
    - uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-dshow
        path: ffmpeg/ffmpeg.exe
