name: Build FFmpeg with dshow (Windows)

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            git
            make
            yasm
            nasm
            
      - name: Configure FFmpeg
        shell: msys2 {0}
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg
          ./configure \
            --enable-gpl \
            --enable-version3 \
            --enable-dshow \
            --disable-w32threads \
            --enable-pthreads || (cat ffbuild/config.log && exit 1)
            
      - name: Build FFmpeg
        shell: msys2 {0}
        run: |
          cd ffmpeg
          make -j$(nproc)
