name: Build FFmpeg with dshow (Windows Native)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install -y git make nasm yasm

      - name: Clone FFmpeg
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg

      - name: Configure FFmpeg
        run: |
          cd ffmpeg
          configure --enable-dshow --enable-gpl --enable-version3 --toolchain=msvc

      - name: Build FFmpeg
        run: |
          cd ffmpeg
          make

      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-binaries
          path: ffmpeg/ff*.exe
