name: Build FFmpeg (Windows)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            git
            yasm
            nasm
            make
            pkg-config
            diffutils

      - name: Clone FFmpeg
        shell: msys2 {0}
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg

      - name: Configure FFmpeg (Minimal)
        shell: msys2 {0}
        run: |
          cd ffmpeg
          ./configure \
            --prefix=/usr/local \
            --enable-shared \
            --enable-gpl \
            --enable-version3 \
            --disable-w32threads \
            --enable-pthreads \
            --enable-dshow

      - name: Build FFmpeg
        shell: msys2 {0}
        run: |
          cd ffmpeg
          make -j$(nproc)
          make install
