name: FFmpeg Windows Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            git
            make
            yasm
            nasm
            diffutils
            pkg-config
            mingw-w64-x86_64-libx264
            
      - name: Build FFmpeg
        shell: msys2 {0}
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg
          ./configure \
            --enable-dshow \
            --enable-gpl \
            --enable-libx264 \
            --disable-w32threads
          make -j$(nproc)
          
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-binaries
          path: ffmpeg/ffmpeg.exe
